### ISSUE TITLE
Scenario Editor crashing the game (Mac OS X, 0.3.0)

### ISSUE THREAD

**Issue by clong8887** [OpenRCT2/OpenRCT2#12756]
OS: Mac OS X Mojave 10.14.6
Version: 0.3.0
Commit/Build: Not sure what this means? But it says "135cc10b4 on HEAD, DEBUG" next to the version number

While working in Scenario Editor, just selecting items to have available, the game closes itself down without warning. It only seems to happen while I am selecting items under scenery items (I think mostly in the trees/walls/small items section but maybe not always). It has not happened while I am selecting rides.

**Comment by clong8887** [comment]
Yeah it doesn’t say anything at all. I don’t think it was a specific scenery item that caused the issues but I suppose it’s possible.

**Comment by clong8887** [comment]
Ok, it still doesn't give me any actual error messages but I think the problem item may be "Geometric Fountain". I can consistently get the game to crash if I move my cursor over the item when going through the Advanced selection menu. No other items seem to be causing the problem, as far as I can tell. I'm not clicking the geometric fountain, just hovering over it.

**Comment by clong8887** [comment]
I tried deleting the relevant file from my ObjData folder but that didn't seem to help. I will try to just avoid hovering over that item for now but hopefully this helps others on the back end.

**Comment by AaronVanGeffen** [comment]
Ah, since you're using a debug build, I'm fairly sure you're running into #11875. The macOS v0.3.0 shouldn't have been a debug build, though. I wonder what went wrong there.

**Comment by clong8887** [comment]
Upon trying to avoid Geometric Fountain it not just that one object, something else (not sure what) in the early G's of that menu seems to also trigger it. I scrolled to the bottom of that list and worked upwards and didn't have any issues until I got to that area of the menu again.

**Comment by AaronVanGeffen** [comment]
If my hypothesis is correct, the builds for #12761 should resolve the problem.

**Comment by AaronVanGeffen** [comment]
The PR in question has been merged, so the assertion should no longer trigger on develop builds.

**Comment by clong8887** [comment]
Hi- sorry I stopped having the problems by avoiding the objects I know to be an issue, but ran into it again today while in an actual park (rather than editor) so I came back.

I'm new to all of this, so could you please explain how I would download and implement the build at #12761?

**Comment by AaronVanGeffen** [comment]
No worries. As the PR has been merged, you can now test the changes by downloading a build of the develop branch instead. You can do this [via GitHub Actions](https://github.com/OpenRCT2/OpenRCT2/actions), [OpenRCT2.org](https://openrct2.org/downloads/develop), or through the OpenRCT2 Launcher.

**Comment by clong8887** [comment]
Ok I downloaded the latest version from the openrct2.org link you gave me but it still crashes. 

The specific object is one of the glass roof objects.

**Comment by AaronVanGeffen** [comment]
Hmm, curious. On the bottom-left corner of the title screen is some version information. Does it still say `DEBUG` over there?

**Comment by clong8887** [comment]
Yeah. It says OpenRCT2, v0.3.0-93(26def8716 on HEAD, DEBUG).

**Comment by janisozaur** [comment]
@AaronVanGeffen why is this closed? Shouldn't we fix errors instead of just hiding them?

**Comment by AaronVanGeffen** [comment]
@janisozaur The actual bug is still tracked in #11875, which is why this was initially marked as a duplicate. The issue presented here was that our macOS release builds still contained assertions. #13012 fixed that.

**Comment by janisozaur** [comment]
I don't exactly see anything wrong with that, this is how we get all or bug reports. Macos builds will just silently corrupt files now.

**Comment by IntelOrca** [comment]
@janisozaur This issue is closed because it is a duplicate: #11875, we don't need two issues for the same bug.
