### ISSUE TITLE
Ride ratings stuck at "Not Yet Available" when operating in modes rather than "Continuous Circuit Mode"

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1630]
The rating would usually display within a short time, but now it doesn't appear at all. (The chairlift has waited to display for at least 15 minutes)

![1007](https://cloud.githubusercontent.com/assets/13048125/8721142/7c2802a2-2bea-11e5-98c9-f8b44b751da7.PNG)
![1007-2](https://cloud.githubusercontent.com/assets/13048125/8721143/7c39c12c-2bea-11e5-8eb6-dc2c20e563bf.PNG)

build tested: [b1007](https://openrct2.com/download/1007) from OpenRCT2.com

edit: tested in Roller Coaster Designer and another save, they are fine, so I attached this save for developers to take a look: (maybe it was corrupted by the earlier builds, I don't know.)
https://drive.google.com/file/d/0B2_12DbzmFxYaUt0R1p5dldFQzA/view?usp=sharing

**Comment by Gymnasiast** [comment]
It should have been fixed recently. Have you tried removing a section of your coasters, building it again and testing it again?

**Comment by daihakken** [comment]
those Coasters are built in this build, while the chairlift was built in some 9xx build.

**Comment by daihakken** [comment]
Experienced this bug again in my new Electric Field by building a power launching looping roller coaster.

**Comment by daihakken** [comment]
@duncanspumpkin Sorry to disturb, but if you have time, please take a look. It's not fixed in the latest build yet.

**Comment by sjoerddebruin** [comment]
Having this with the cable lift....
