### ISSUE TITLE
Chairlifts restricted to one car on Station to Station mode

### ISSUE THREAD

**Issue by Wolfscopez** [OpenRCT2/OpenRCT2#2216]
As the title says
![ss 2015-11-06 at 02 38 02](https://cloud.githubusercontent.com/assets/14800654/10987015/21ae0b48-8494-11e5-87ae-b28350883ad3.png)

**Comment by duncanspumpkin** [comment]
I could only reproduce this if I really messed with the stations. If you connect a station back to front it will count as only 1 piece long. I think that is what you have done.

**Comment by Wolfscopez** [comment]
Yeah, that's correct, I accidentally connected it back to front, sort of a bug but not so much, a bug because of the game only counting the station as 1 block long and not longer.

**Comment by e-foley** [comment]
I'm getting additional weird behavior in OpenRCT2 (as of build 1510).

I start with a very simple chairlift ride, three station pieces followed by three straight pieces then three station pieces again.  The ride is able to be tested as expected.

![chairs_1510_simple](https://cloud.githubusercontent.com/assets/6338134/11679475/43520a20-9e06-11e5-940b-4cb5cc5a6c31.png)

When edit the middle section to connect to the "back" of the second station, I get different error messages depending on the version.

**OpenRCT2 build 1510**
![chairs_1510_b](https://cloud.githubusercontent.com/assets/6338134/11679501/6b318aa2-9e06-11e5-84a1-dcf82860e0d8.png)

**Vanilla (GOG Triple Thrill Pack)**
![chairs_vanilla_b](https://cloud.githubusercontent.com/assets/6338134/11679517/7ed0c0fa-9e06-11e5-9cdf-03d5e024c57a.png)

The vanilla game offers more info in the error message, even though it's not necessarily more useful.

In both of these cases, I'm able to select six or seven chairs as opposed to just one, signalling that there may be two intertwined issues at play.

**Comment by duncanspumpkin** [comment]
Solution is to not do that.

**Comment by e-foley** [comment]
"Don't trigger the bug" isn't the same as fixing the bug.

**Comment by Gymnasiast** [comment]
@duncanspumpkin : A strange answer. The screenshot shows a configuration that should be valid, yet shows an error. That is a bug, and should be fixed.

**Comment by IntelOrca** [comment]
An original bug if I understand correctly?

**Comment by IntelOrca** [comment]
Perhaps @duncanspumpkin means there is currently no work around until the original bug is fixed.

**Comment by Gymnasiast** [comment]
Well the issue seems to be that the checking code can't handle the station pieces being (technically) reversed. Not sure whether that's currently solveable.

**Comment by Dracheron** [comment]
As of 0.4.31 the bug still persists, as I accidentally managed to trigger the bug unknowingly while making a scenario.  Perhaps if its possible we track each station by their absolute identity and then get that station's length that you could get a valid configuration but that I'm not sure on

**Comment by voidxor** [comment]
I haven't updated to 0.4.31 yet, but I can confirm that I found it in 0.4.30 the other day.

There are two distinct issues here. The first occurs when track is connected front-to-front or back-to-back, as described and pictured in @e-foley's 2015 comment. While this could be described as user error, and can happen to most any tracked ride (such as coasters), it's easier to make this mistake when building a chairlift because chairlift track appears bidirectional.

It would be neat to add logic to OpenRCT2 to self-right the track direction when a player inadvertently connects something front-to-front or back-to-back, especially for chairlifts. However, I foresee this taking a good chunk of programming effort to make it happen.

The second issue is what bit me the other day. I started by building Station 1, and then worked my chairlift layout backward before finishing with Station 2. So no track elements were touching front-to-front or back-to-back. It was simply that Station 2 was behind Station 1 (referring to the direction that guests sit when loading, as well as the directional arrows during construction).

From what I can tell, this second issue exists in RCT2 and OpenRCT2, but not in RCT1.

**Comment by jubwub** [comment]
> The second issue is what bit me the other day. I started by building Station 1, and then worked my chairlift layout backward before finishing with Station 2. So no track elements were touching front-to-front or back-to-back. It was simply that Station 2 was behind Station 1 (referring to the direction that guests sit when loading, as well as the directional arrows during construction).

I just had the same issue, trying to build a chairlift in reverse and being locked to only 1 chair. Had to build a second chairlift from scratch in the opposite order to make it work even though it ended up being the same exact design, just Station 1 was the opposite station.

**Comment by voidxor** [comment]
> I just had the same issue, trying to build a chairlift in reverse and being locked to only 1 chair. Had to build a second chairlift from scratch in the opposite order to make it work even though it ended up being the same exact design, just Station 1 was the opposite station.

What version of OpenRCT2 are you running?

**Comment by jubwub** [comment]
> What version of OpenRCT2 are you running?

v0.5.4 for Linux (x86-64)
