### ISSUE TITLE
People getting lost in OpenRCT2, but not in RCT2

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2499]
People in the red circle are getting lost trying to find rides like the Grand National (marked with a yellow circle), even though there is quite a clear path to it. This did not happen in RCT2.
![scr129b](https://cloud.githubusercontent.com/assets/1478678/11820125/20cea2b2-a363-11e5-907e-91fa81ff6e5e.jpg)

**Comment by janisozaur** [comment]
Do they have maps or bears/toys?

**Comment by Gymnasiast** [comment]
Hardly anyone has toys, almost all of them have maps. I know this behaviour was changed in OpenRCT2. However, the path they should take is so straightforward I'm not sure this is actually the cause, although it might be.

**Comment by duncanspumpkin** [comment]
A straight forward path would be a direct path that does not require them to walk away from the location. Since you have a U shape they will get to the corner of the U and turn back on themselves as they think that route would be closer. I don't see how this didn't happen in vanilla. Its possible that something is breaking the last direction.

**Comment by Gymnasiast** [comment]
On closer inspection, I noticed the following behaviour in the red circle:

People coming from the bottom left will _never_ turn left at the banners, only go back. That could explain why they cannot reach Grand National. That behaviour looks suspiciously like #1377. It could be that the fixed map check in OpenRCT2 just makes this error more visible.

![scr133](https://cloud.githubusercontent.com/assets/1478678/11820928/3e970f92-a367-11e5-975c-5ae8824a7a69.png)

**Comment by IntelOrca** [comment]
Why are peeps allowed to reverse direction?

**Comment by Gymnasiast** [comment]
As I said above, I tested it with and without allowing reversing. Normally the AI will not reverse a peep unless it is forced to do so. In this case the peeps will always reverse (as if they can't turn left) if they can reverse, and when I prevent them from reversing they _will_ turn left but forget their destination.

**Comment by IntelOrca** [comment]
Another report:
https://www.reddit.com/r/rct/comments/3xx0m2/2_can_someone_enlighten_me_on_why_my_peeps_are/

**Comment by raidcookie** [comment]
As already described in [this entry](http://rct.wikia.com/wiki/Paths#Pathing_Systems), Peeps can not get lost if the path to their destination has no decision points, such as intersections. 

Why they don't turn left, however, is unclear. I have noticed that peeps will not walk on paths that are occupied by an object that was built in Zero Clearance. They also don't seem to use a few path tiles to the left at all.

**Comment by Gymnasiast** [comment]
@raidcookie : The points is that there are some OpenRCT2-specific bugs. The one you describe is from the original RCT2 and the result of limitations of the peep AI, not an outright bug.

**Comment by IntelOrca** [comment]
Well there still might be RCT2 peep AI bugs which cause it to be worse that was originally designed.

**Comment by Broxzier** [comment]
The guests in this park are trying to leave, but keep walking on the same 3x3 square.
[Community Park V2.44.zip](https://github.com/OpenRCT2/OpenRCT2/files/77666/Community.Park.V2.44.zip)
![](http://i.imgur.com/8GgTqX2.png)
Hopefully this save proves useful for debugging.

**Comment by LRFLEW** [comment]
Looking at @Broxzier's park, I found something very concerning. It looks like a lot of guests are looking for the 5^th exit (a park can only have 4), with a few looking for the 73^rd exit (aka, values of 4 and 72). Since the exit being searched for shares the same address space as a ride (either searching for or riding, I don't know right now), my guess is that either some of these guests shouldn't be looking for the exit or they had the `PEEP_FLAGS_PARK_ENTRANCE_CHOSEN` flag set erroneously.

**Comment by LRFLEW** [comment]
BREAKTHROUGH! I found (one) cause for this. The variable `peep->current_ride` has double-duty. Most of the time, it keeps track of the ride a guest is on for the messages like "Guest is on Looping Coaster 2". However, when a guest is leaving the park, the path finding code uses that variable to determine which exit the guest should head to (which is needed for parks with multiple exits in very different locations). This usually works fine, but at some point code was added (?) that allowed for leaving guests to take transport rides to the exit. This has the problem of having the guest search for possibly invalid exits once they leave the ride. I'll make a PR for what I was able to do to fix the issue, but if this bug wasn't added from a feature addition, then it might need assembly cross-referencing to fix.

**Comment by Gymnasiast** [comment]
Good to see! However, that doesn't cover the whole problem: in my park, people were getting lost while heading to a ride.

**Comment by LRFLEW** [comment]
Sure, it doesn't cover everything, but it's at least a significant factor if it isn't an original bug. I can take a look at your save if you upload it here.

**Comment by marijnvdwerf** [comment]
@Gymnasiast Are they still getting lost in the latest development builds? I have a feeling that 2e72d3c44704bb0e4aaa3ae105dcf19ab43ec5f might have changed this.

**Comment by IntelOrca** [comment]
@marijnvdwerf I think that was an original bug so possibly not.

**Comment by LRFLEW** [comment]
I'm not sure how much of this is an original bug. I have a feeling this might be a bit of confirmation bias, as people in OpenRCT2 are more likely to build larger parks with more wide paths. After decompiling sub_69A997, it does look like the algorithm used to determine the next path-finding direction could be heavily improved. I plan on experimenting with variants of the algorithm, but if someone would be willing to provide a large map with (preferably) existing pathfinding issues, it would help a lot.

**Comment by IntelOrca** [comment]
But I think this issue is about a saved game which when loaded in OpenRCT2 behaves worse than when loaded in RCT2 suggesting that OpenRCT2 is degrading the peep AI.

Its a question of whether this is just all to do with our bug fix with the park maps or something else.

**Comment by LRFLEW** [comment]
I've said this before, and I'll say it again. Could somebody ( @Gymnasiast ?) provide a save for this. Bronzer's save had a different issue, and I haven't yet seen a save with what IntelOrca is describing from my testing.

**Comment by Broxzier** [comment]
I've got a new save (same park, never version) of people being 'stuck' in OpenRCT2, while they manage to find their ways in RCT2 easily.

[Community Park V2.55a.sv6.txt (remove extension)](https://github.com/OpenRCT2/OpenRCT2/files/93155/Community.Park.V2.55a.sv6.txt)

**Comment by LRFLEW** [comment]
Thank you for the save game @Broxzier. I took a look at it in both OpenRCT2 and the Original, and I can confirm that there is a problem that is not an original bug. I'll look into it and see what I can find.

**Comment by Gymnasiast** [comment]
Sorry for not posting a link earlier. Here is one to my park: https://www.dropbox.com/s/ke76ngnks4ion6a/Pakhuis%20-%20Derde%20Alter%20Ego%20-%20fixedMR.sv6?dl=0

Here is another strange case: people were apparently unable to leave the restaurant slightly above the centre of the image. After forcing them out with a No Entry banner, they instead gathered for a time in the area slightly to the bottom right of the centre. Note that in this case it's people leaving the park, but it also affects people that don't.

![scr147](https://cloud.githubusercontent.com/assets/1478678/12376954/434bcc94-bd0c-11e5-9ada-f1937c0ee8e6.png)

**Comment by LRFLEW** [comment]
@Gymnasiast Thank you for the save. I'm currently investigating the issue that Bronzier brought up, so it may be a little while before I get to your save specifically, but I will take a look at it as well. I want to see this issue resolved, and having spent some time now with the pathfinding code, I should be able to figure out what's going on.

**Comment by LRFLEW** [comment]
@Gymnasiast I'm having trouble opening your save file. It's complaining with a bunch of "failed to load entry" errors. I'm assuming it's custom scenery I don't have. Can you link to the custom scenery you used? Is it possible to include the custom scenery in the save?

**Comment by Gymnasiast** [comment]
@LRFLEW: It should list missing scenery in the console. I also used some WW and TT objects in that save.

**Comment by LRFLEW** [comment]
@Gymnasiast It's a very long list of 247 objects. It would clutter the issue if I posted them here, so I pastebin-ed the list here: http://pastebin.com/icB4VY1E

**Comment by Gymnasiast** [comment]
This should contain 245 of the missing objects. Could you import those and report which two are still missing?

[to-lrflew.zip](https://github.com/OpenRCT2/OpenRCT2/files/130452/to-lrflew.zip)

**Comment by Gymnasiast** [comment]
Here are the other two:

[to-lrflew-2.zip](https://github.com/OpenRCT2/OpenRCT2/files/130559/to-lrflew-2.zip)

**Comment by Gymnasiast** [comment]
People coming from the yellow path file are unable to turn left on the brown tile. They even turn around, though they wouldn't normally do that (normally they would go to the left or the right).

![scr181](https://cloud.githubusercontent.com/assets/1478678/13581729/98069304-e4a8-11e5-857f-c50b9e716ca9.png)

**Comment by janisozaur** [comment]
Park from https://github.com/OpenRCT2/OpenRCT2/issues/2499#issuecomment-172310104 with all the objects embedded. Remove `.txt` extension.

[2499_export.sv6.xz.txt](https://github.com/OpenRCT2/OpenRCT2/files/162140/2499_export.sv6.xz.txt)

**Comment by Nubbie** [comment]
I wonder if anything has to do with the original 'Death Trap' bug too
Especially when they are leaving the park
#3261

**Comment by Broxzier** [comment]
Someone on the forums posted another park with the same issue.

Screenshot of RCT2: http://i.imgur.com/wcUGrpi.png
Screenshot of OpenRCT2: http://i.imgur.com/SqhYYum.png
Saved game: [Bad Peep Ai.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/222105/Bad.Peep.Ai.sv6.txt)

**Comment by marijnvdwerf** [comment]
If someone wants to tackle this. It already occurred in `0.0.2`, so that probably limits the number of possible places to look.

**Comment by Christipher** [comment]
Judging by that first picture, I think what's going on is that it's being caused by the Death traps a few other issues have referenced (on a more serious scale) - could someone see if that happens to be the case?

**Comment by Gymnasiast** [comment]
@Christipher That's not the cause. Not turning left and death traps are two wholly differently things.

**Comment by player49256** [comment]
As adviced, I'm posting this in already open issue, reporting my findings here:

OS: Windows 10
Version: 0.0.5
Commit/Build: 0.0.5.0 build ca06bbe

Guests seem to get stuck alot and seems to leave park at a fast rate
More details around all this and download to save file is here:
https://openrct2.org/forums/topic/1462-guest-count-plumit-whenever-i-open-my-park-in-openrct2/

    Reproducible in RCT2 (vanilla)?
    Multiplayer?

Steps to reproduce:
1. Visit link above and look at screenshots
2. Download save file in zippyshare link
3. Open savefile in both OpenRCT2 and Vanilla RCT2
4. Watch the diffrence in guest count, and how guests seem to get stuck in OpenRCT2

Dump file
No dump file

Screenshots / Video:
Alot of Screenshot links in forum topic
https://openrct2.org/forums/topic/1462-guest-count-plumit-whenever-i-open-my-park-in-openrct2/

Save game:
http://www70.zippyshare.com/v/g7rbgSWY/file.html

**Comment by janisozaur** [comment]
@player49256 can you please post the file directly on github instead of external host? They tend to expire, be blocked via ISP, cannot be downloaded without a browser or have other issues.

**Comment by player49256** [comment]
> can you please post the file directly on github instead of external host? They tend to expire, be blocked via ISP, cannot be downloaded without a browser or have other issues.

Yes I tried, but noticed i could only do it from Internet Explorer.
The file is now uploaded in previous post and in link below:
https://github.com/OpenRCT2/OpenRCT2/files/369125/Chrisses.Wonderworld.zip

**Comment by Gymnasiast** [comment]
This looks solved by #4221 :+1:

**Comment by zaxcav** [comment]
Post #4211 it looks likes peeps trying to exit the park are now getting stuck between the high-rise and large maze (left side of the image at the top of this issue).
Reopen this issue?
The use of queue paths as normal paths in this park might be causing this here.

**Comment by zaxcav** [comment]
Confirmed.  The new thin junction detection in #4211 did not anticipate queue paths being used as regular paths and incorrectly classifies some junctions.  It's an easy fix.  I'll get a PR for this done today.

**Comment by player49256** [comment]
This seems still not to be fixed, tested with 0.0.5.0 build 6b2082f

Load this savefile: https://github.com/OpenRCT2/OpenRCT2/files/369125/Chrisses.Wonderworld.zip

Move towards the north entrance, follow peoples who enter the park, watch how they move before they exit the park.
They seem to be stuck in the first mall, and even at the Information Kiosks at the beginning.

This did not happen in Vanilla (as guest count still plumits to 800 in OpenRCT2 but increase in Vanilla to 3600).

You can go to the thoughts panel, watch all who "Wants to go home" and check the map where they are, almost all are close to the north entrance.

I can provide pictures if requested.

**Comment by zaxcav** [comment]
The original problem reported in this issue was with the pathfinding - meaning the peeps who had decided to do something (buy food/drink, go on a ride, leave the park) were having trouble getting to their destination (and thinking they are lost because it was taking too long to get there).  Looking at the provided savegame I don't see any obvious pathfinding issues in the area indicated - people that have decided on an action are having no trouble getting to their destination.

I watched a few peeps (hungry and thirsty) enter the park, buy food and drink and then decide to leave.  They did not think they got lost or have any problem getting to the shops they chose, nor getting to the exit.

If peeps are deciding to leave the park rather than staying and doing other things, then this is a different issue.

I don't know anything about the peep AI for making decisions on what to do while in the park.
Hopefully someone else can comment on this.

**Comment by player49256** [comment]
@zaxcav 
Just tried in Vanilla, and as you say, it seems to happen there aswell.
However, there's still a huge difference in guest count.

So I did some testing, and every single one of new guests that entered had full need for food and drink (red bar), some were happy and some mad.
Before they managed to finish both their food and drink, they wanted to leave park. They were inside park for max 5 min, except two who is still inside actually riding rides.
(That makes me wonder if all 6 guests would leave on OpenRCT2).

So that lead me to beleive some things are not how it's supposed to be:
1. Are every single guest supposed to have full bar in hunger and thirst when they enter?
2. Does the function of an actuall working map have any effect on this?

If you look at the picture below, the 6 first guests have just entered.
But the 7th guest in the bottom, have been in the park for 8(!) hours.
http://imgur.com/a/dPZOD
![rctvanilla](https://cloud.githubusercontent.com/assets/20512002/19124454/926dcfde-8b33-11e6-9a3d-e2c722d4d360.PNG)

Maybe this is a seperate issue? But something is really off, which makes vanilla RCT2 able to keep above 3k guests inside the park, while OpenRCT2 barely manages 1k.

**Comment by zaxcav** [comment]
The affects of OpenRCT2 having working peep maps are:
1. peeps will choose things to do from anywhere on the map, rather than from only the nearby things +  "big" rides (i.e. highest drop height exceeds a threshold or excitement >= 8.00)
2. the pathfinding limits are expanded compared to without a map.

As this is a different issue to #2499 this discussion should be moved to a new issue.
We can't expect other developers to follow this discussion when it's in a closed issue.

I looked into why your peeps are leaving the park. This is a brief description of how the OpenRCT2 code currently works.  I know nothing more about this part of the code than what I've learned investigating this just now. I also don't know how the logic in OpenRCT2 differs from the vanilla logic.

All peeps that have been in the park for 5mins and haven't yet been on any ride are forced to pick a ride to go on.
If they don't pick a ride, they leave.
Peeps that are not walking (e.g. sitting) or have food will not pick a ride.

So, in order to keep guests in your park longer you need to encourage them to get onto a ride in the first 5 mins.  I would suggest you move your food court further away from the entrance and/or put more rides between the entrance and the food court.

**Comment by zaxcav** [comment]
Created new issue #4539 for peeps leaving after 5mins more often than in vanilla.
Any further discussion should occur in issue #4539.
