### ISSUE TITLE
OpenRCT2 dedicated server crash

### ISSUE THREAD

**Issue by EzioisAwesome56** [OpenRCT2/OpenRCT2#7146]
OS: Windows 10 Pro x64
Version: 0.1.1
Commit: 4601265

Im not exactly sure what happened, but i was running a dedicated server and it crashed randomly after school today. me and my friends where not doing anything out of the ordinary, just playing the game and building things when the server crashed out of nowhere. I got the error attached below and after clicking abort, told me it generated a dump file + dump save and to upload it here.

Im not sure even how to reproduce it, as we were not doing anything out of the typical building stuff (dont know about my friends, though) but reopening the dump save causes the same error

Attached below is a picture of the first error and a zip with both the dump file and dump save.
![error](https://user-images.githubusercontent.com/21185626/35944417-507d026a-0c2a-11e8-9f6d-d4ce5becd2dd.png)
[openrct2crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/1704926/openrct2crash.zip)

**Comment by janisozaur** [comment]
Do you have any related sv6? Some autosave maybe?

**Comment by EzioisAwesome56** [comment]
I have autosaves yeah, do you want me to upload them?

**Comment by Gymnasiast** [comment]
Could you upload all mentioned saves?

I also noticed you're on an a 'release' build. This bug may very well have been solved in the meantime. Generally, we recommend using 'develop'. If problems happen, we recommend older 'develop' versions.

**Comment by EzioisAwesome56** [comment]
Alright so i looked at my autosaves on both the server pc and a client that played on the server before the crash, and all i found where autosaves from today, so i dont know what happened to them (i also dont think the dedicated server itself autosaves or saves)

I do still have the save from the client shortly before the server crashed, so ive attached it below

side note: i got home today from school and the server hadnt crashed, unlike yesterday when it did, so i really have no idea what happened
[shortly before crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/1708852/shortly.before.crash.zip)

**Comment by EzioisAwesome56** [comment]
it happened again, i left the server up over the weekend and it crashed with a similar error
i have attached the dump files and a picture of the error with the console in the background
![error2](https://user-images.githubusercontent.com/21185626/36075073-2d280144-0f17-11e8-9ac7-7350fbe618ec.png)
[Dump2.zip](https://github.com/OpenRCT2/OpenRCT2/files/1714505/Dump2.zip)

note this was on a different save then the last crash

**Comment by Gymnasiast** [comment]
Really, we cannot do much unless you can reproduce this on a current develop build. The code has changed a lot in the meantime.

**Comment by EzioisAwesome56** [comment]
fair enough, i shall see if it happens again on dev.

**Comment by EzioisAwesome56** [comment]
so i got a "crash" on develop today, i think atleast. I cant tell what version as it just updated itself today, but me and a friend where playing in the morning today when it disconnected us both, then it wouldnt let us reconnect. I got home and control-c'd it and got the error below, no other messages or errors where shown by the game. It didnt allow connections from localhost either, it just said no data. No dump file was created either
![deverror](https://user-images.githubusercontent.com/21185626/36176029-58abf392-10df-11e8-99a9-5a598350eb96.png)

**Comment by Gymnasiast** [comment]
That doesn't show a crash, though. At that line there is code to handle that sort of thing. So I'm not sure why it wouldn't let you reconnect. It might have crashed elsewhere.
